#!/bin/sh
git filter-branch --env-filter '
OLD_NAME="Roman Savelev"
OLD_EMAIL="romansavelev@MacBook-Air-Roman.local"
CORRECT_NAME="Roolman"
CORRECT_EMAIL="roman-savelev4@yandex.ru"
if [ "$GIT_COMMITTER_NAME" = "$OLD_NAME" ]
then
    export GIT_COMMITTER_NAME="$CORRECT_NAME"
    export GIT_COMMITTER_EMAIL="$CORRECT_EMAIL"
fi
if [ "$GIT_COMMITTER_NAME" = "$OLD_NAME" ]
then
    export GIT_AUTHOR_NAME="$CORRECT_NAME"
    export GIT_AUTHOR_EMAIL="$CORRECT_EMAIL"
fi
' --tag-name-filter cat -- --branches --tags